let date= new Date()
console.log(date)
console.log(date.toString())
console.log(date.toDateString())
console.log(date.toISOString())
console.log(date.toJSON())
console.log(date.toLocaleDateString())
console.log(date.toLocaleTimeString())
console.log(typeof date)
// let myDate= new Date('december 5 1997')
// console.log(myDate.toString())
// console.log(Date.now.toLocaleTimeString('en-IN'))
let myBirthday= new Date('december 5 2024');
let recentDate= Date.now()
console.log(recentDate)
console.log(myBirthday.getTime()/1000)
console.log(myBirthday.getMonth()+1)
console.log(myBirthday.getDay())